### PR TITLE
feat: upgrade to manifest v3 & upgrade lock

### PR DESCRIPTION
**Pull request by YunYouJun**
### Description

- Now, we have to migrate to manifest v3 from v2. https://developer.chrome.com/docs/extensions/migrating/checklist/
- upgrade pnpm@8 lock

### Additional context

By the way, `getCurrentContext` had been deprecated in `webext-bridge@6`.
Should we remove it?

https://github.com/zikaari/webext-bridge/blob/79c9f4b6a31b9b7bcdad9c13e7d4111d51338651/CHANGELOG.md?plain=1#L17

### CODE REVIEW

**Comment by antfu** [comment]
Feel free to do the refactoring for webext-bridge

**Comment by tmkx** [comment]
This PR doesn't work in dev, there are still some things to do when migrating to mv3:

- background script output in dev
- HMR(or downgrade to watch-mode build)

**Comment by antfu** [comment]
I am not active in developing web extensions recently. @tmkx @YunYouJun, please feel free to collaborate together, you can push and merge things where you think are necessary with out. Or you can ping me to review when there is something uncertain. Thanks!

**Comment by YunYouJun** [comment]
Sorry, I only checked the build after submitting it to the Google Store.
It has been approved by the store for release and is working, so the dist file should be fine. https://github.com/YunLeFun/your-popup

I'll check out the development hot update.

**Comment by tmkx** [comment]
never mind, let’s move forward to support MV3 :)

**Comment by this-oliver** [comment]
Legends!!!!

**Pull request merged**
